# Generated by Django 5.2.4 on 2025-08-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["identifier"],
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
            },
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["identifier"], name="core_questi_identif_bfcb1d_idx"
            ),
        ),
    ]
