# Generated by Django 5.2.4 on 2025-08-05 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_alter_question_options_and_more"),
        ("pokemons", "0002_alter_pokemon_options_pokemon_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_score", models.FloatField(help_text="Overall match score")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_results",
                        to="pokemons.pokemon",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_results",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match Result",
                "verbose_name_plural": "Match Results",
                "ordering": ["-total_score", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_profile", "-total_score"],
                        name="matcher_mat_user_pr_c084f7_idx",
                    )
                ],
            },
        ),
    ]
