# Generated by Django 5.2.4 on 2025-08-05 14:11

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
                ("habitat", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "abilities",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("flavor_text", models.TextField(blank=True, null=True)),
                ("hp", models.IntegerField()),
                ("attack", models.IntegerField()),
                ("defense", models.IntegerField()),
                ("special_attack", models.IntegerField()),
                ("special_defense", models.IntegerField()),
                ("speed", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
