# Generated by Django 5.2.4 on 2025-08-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemons", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pokemon",
            options={
                "ordering": ["name"],
                "verbose_name": "Pokemon",
                "verbose_name_plural": "Pokemons",
            },
        ),
        migrations.AddField(
            model_name="pokemon",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="pokemon",
            index=models.Index(fields=["name"], name="pokemons_po_name_1d3bf0_idx"),
        ),
        migrations.AddIndex(
            model_name="pokemon",
            index=models.Index(fields=["types"], name="pokemons_po_types_0df55f_idx"),
        ),
        migrations.AddIndex(
            model_name="pokemon",
            index=models.Index(fields=["color"], name="pokemons_po_color_eeaa9e_idx"),
        ),
        migrations.AddIndex(
            model_name="pokemon",
            index=models.Index(
                fields=["habitat"], name="pokemons_po_habitat_7e5db5_idx"
            ),
        ),
    ]
