# Generated by Django 5.2.4 on 2025-08-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemons", "0002_alter_pokemon_options_pokemon_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="cries_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="popularity_score",
            field=models.IntegerField(default=0),
        ),
    ]
